# config.py
MODEL = "gemma3:4b"
PORT = 5000

TOUCH_DISTANCE = 200

HUNGER_MIN = 0
HUNGER_MAX = 100
HUNGER_EAT = 30
HUNGER_INCREASE = 1

ENERGY_MIN = 0
ENERGY_MAX = 100
ENERGY_RESTORE = 30
ENERGY_DECREASE = 1

CURIOSITY_MIN = 0
CURIOSITY_MAX = 100
CURIOSITY_INCREASE = 1
CURIOSITY_DECREASE = 2

FIXATION_TARGET_COUNT = 5

MEMORY_MAX_SIZE = 100
MEMORY_CONTEXT_SIZE = 10

WAIT_TIME_MIN = 8
WAIT_TIME_MAX = 20
WAIT_TIME_DEFAULT = 10
