# config.py
MODEL = "gemma3:4b"
PORT = 5000

SPHERE_RADIUS = 1500
TOUCH_DISTANCE = 200

HUNGER_INCREASE = 1
ENERGY_DECREASE = 1
HUNGER_MAX = 100
ENERGY_MIN = 0

CAMPFIRE_HUNGER_RESTORE = 30

MEMORY_MAX_SIZE = 10
MEMORY_CONTEXT_SIZE = 3

WAIT_TIME_MIN = 8
WAIT_TIME_MAX = 20
WAIT_TIME_DEFAULT = 10